### ISSUE TITLE
No module named "resource"

### ISSUE THREAD

**Issue by Prasanta-Hembram** [thammegowda/nllb-serve#2]
Hi, I'm using windows 11 and followed all the steps, but when I started Serve using nllb-serve command I got these following error.
![image](https://user-images.githubusercontent.com/51163799/206170590-2b6fad54-9a5b-47d2-a1c9-b6216bf3a782.png)

**Comment by MirrorCY** [comment]
same issue

**Comment by thammegowda** [comment]
I had not tested on Windows command prompt and powershell environment. 
The issue here is `resource` module from  python std lib https://docs.python.org/3.9/library/resource.html doesnt exist on windows and only exists on unix platforms (mac and linux).  I didnt know this!

We can remove dependence on `resource` module (it is used for logging memory usage only). 
Option 1: please remove dependence on resource module. pull requests are welcome!
option 2: use WSL and it will work out of the box

**Comment by thammegowda** [comment]
Fixed it https://github.com/thammegowda/nllb-serve/commit/846541b022ff2573e4fcdaeaae3d695d829389aa
